site_name: Ahmad Sidik
theme:
  name: material
  extra:
  material:
    custom_dir: 'assets'
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.instant.progress
    - navigation.indexes
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.annotation
    - content.code.copy
    - toc.integrate
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: white
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: black
      accent: lime
# add more section in table of content
markdown_extensions:
  - toc:
      toc_depth: 10
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

